version: '3'

services:
  postgres:
    container_name: 3as-postgres-db
    image: 'postgres:13.1-alpine'
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    container_name: 3as-redis-db
    image: 'bitnami/redis:6.0.16'
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  pg-data:
    driver: local