version: '3'

services:
  backend-application:
    build:
      context: ../../../
      args:
        POSTGRES_URL: ${DB_URL}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASS: ${DB_PASS}
        REDIS_HOST: ${REDIS_HOST}
        REDIS_PORT: ${REDIS_PORT}
        REDIS_PASS: ${REDIS_PASSWORD}
        TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
        TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
        TELEGRAM_BOT_WEBHOOK_PATH: ${TELEGRAM_BOT_WEBHOOK_PATH}
        FRONTEND_URL: ${FRONTEND_URL}
        JKS_KEYSTORE_NAME: ${JKS_KEYSTORE_NAME}
        JKS_KEY_ALIAS: ${JKS_KEY_ALIAS}
        JKS_KEYSTORE_PASSWORD: ${JKS_KEYSTORE_PASSWORD}
        JKS_KEY_PASSWORD: ${JKS_KEY_PASSWORD}
        JKS_TRUSTSTORE_NAME: ${JKS_TRUSTSTORE_NAME}
        JKS_TRUSTSTORE_PASSWORD: ${JKS_TRUSTSTORE_PASSWORD}
    container_name: backend-application
    ports:
      - '${BACKEND_PORT}:8443'
    environment:
      AAAS_POSTGRES_URL: ${DB_URL}
      AAAS_POSTGRES_USER: ${DB_USER}
      AAAS_POSTGRES_PASS: ${DB_PASS}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BOT_WEBHOOK_PATH: ${TELEGRAM_BOT_WEBHOOK_PATH}
      FRONTEND_URL: ${FRONTEND_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASSWORD}
      JKS_KEYSTORE_NAME: ${JKS_KEYSTORE_NAME}
      JKS_KEY_ALIAS: ${JKS_KEY_ALIAS}
      JKS_KEYSTORE_PASSWORD: ${JKS_KEYSTORE_PASSWORD}
      JKS_KEY_PASSWORD: ${JKS_KEY_PASSWORD}
      JKS_TRUSTSTORE_NAME: ${JKS_TRUSTSTORE_NAME}
      JKS_TRUSTSTORE_PASSWORD: ${JKS_TRUSTSTORE_PASSWORD}

  frontend-application:
    build:
      context: ../frontend/
      args:
        BACKEND_APP_URL: ${BACKEND_URL}
        SSL_CERT_PATH: ${SSL_CERT_PATH}
        SSL_KEY_PATH: ${SSL_KEY_PATH}
    container_name: frontend-application
    ports:
      - '${FRONTEND_PORT}:3000'
    restart: always
    depends_on:
      - backend-application